services:
  - postgresql
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  
env:
  global:
     - GO111MODULE="travis"
language: go
go:
  - 1.15
env:
  - "PATH=/home/travis/gopath/bin:$PATH"

before_install:
  - cd backend
  - go mod download

script:
	

